version: '3.8'

services:
  admin_auth_service:
    build:
      context: ../Admin/auth
      dockerfile: Dockerfile 
    container_name: menara
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=menara
      - DB_PASSWORD=daman12345
      - DB_NAME=menara
    depends_on:
      - postgres
    image: golang:1.21.0 

  postgres:
    image: postgres:16.0
    container_name: postgres_db  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daman12345
      POSTGRES_DB: menara
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
