version: '3.8'

services:

  authentication_service:
    build: 
      context: ./authentication/admin
    container_name: auth_service
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daman12345
      POSTGRES_DB: admin
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daman12345
      POSTGRES_DB: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
